### ISSUE TITLE
clang support depends on GNU libstdc++

### ISSUE THREAD

**Issue by stspdotname** [tsaarni/cpp-subprocess#5]
The current wording used in README.md is somewhat misleading regarding clang support.

While README.md claims cpp-subprocess worked with clang, that claim should be taken with a grain of salt: cpp-subprocess won't compile with stock clang because of the dependency on GNU's ext/stdio_filebuf.h extension which is not present in clang's own C++ library.
So cpp-subprocess will only compile with clang as long as GNU's C++ standard library is used.

**Comment by tsaarni** [comment]
Thanks for clarification!
